ALTER TABLE users ADD COLUMN country VARCHAR(100) DEFAULT '' AFTER bio;
ALTER TABLE users ADD COLUMN phone_code VARCHAR(10) DEFAULT '' AFTER country;
ALTER TABLE users ADD COLUMN address VARCHAR(255) DEFAULT '' AFTER phone_code;
ALTER TABLE users ADD COLUMN city VARCHAR(100) DEFAULT '' AFTER address;
ALTER TABLE users ADD COLUMN state VARCHAR(100) DEFAULT '' AFTER city;
ALTER TABLE users ADD COLUMN zip_code VARCHAR(20) DEFAULT '' AFTER state;
