<?php
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/admin-session.php';
requireAdminLogin();
$admin = getCurrentAdmin();
$nav_type = 'admin'; $active_nav = 'users';
$page_title = 'Manage Users'; $page_subtitle = 'View, edit, and manage all user accounts';
require_once __DIR__ . '/../includes/argon-header.php';
?>

<div class="card" style="margin-bottom:1.25rem"><div class="card-body"><div style="display:flex;flex-wrap:wrap;gap:.75rem;align-items:flex-end">
    <div style="flex:1;min-width:200px"><label style="font-size:.78rem;font-weight:600;color:var(--argon-dark);display:block;margin-bottom:.25rem">Search</label><input type="text" id="searchInput" placeholder="Name or email..." style="width:100%;padding:.45rem .6rem;border:1px solid var(--argon-border);border-radius:.25rem;font-size:.82rem" onkeyup="debounceSearch()"></div>
    <div><label style="font-size:.78rem;font-weight:600;color:var(--argon-dark);display:block;margin-bottom:.25rem">Status</label><select id="statusFilter" onchange="loadUsers()" style="padding:.45rem .6rem;border:1px solid var(--argon-border);border-radius:.25rem;font-size:.82rem"><option value="">All</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="banned">Banned</option></select></div>
</div></div></div>

<div id="usersList" class="card tsec"><div class="tscroll"><table><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>Balance</th><th>Status</th><th>KYC</th><th>Joined</th><th>Actions</th></tr></thead><tbody><tr><td colspan="8" style="text-align:center;color:var(--argon-muted)">Loading...</td></tr></tbody></table></div></div>
<div id="pagination" style="display:flex;justify-content:center;gap:.5rem;margin-top:1rem"></div>

<div id="detailModal" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:200;align-items:center;justify-content:center"><div class="card" style="max-width:700px;width:90%;max-height:90vh;overflow-y:auto"><div class="card-header" style="display:flex;justify-content:space-between;align-items:center"><h6>User Detail</h6><button onclick="hideDetailModal()" style="background:none;border:none;font-size:1.25rem;cursor:pointer;color:var(--argon-muted)">&times;</button></div><div id="detailContent" style="padding:1rem"></div></div></div>

<div id="editModal" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:200;align-items:center;justify-content:center"><div class="card" style="max-width:460px;width:90%"><div class="card-header"><h6>Edit User</h6></div><div class="card-body"><form id="editForm" style="display:flex;flex-direction:column;gap:.75rem"><input type="hidden" name="id" id="editUserId"><div><label style="font-size:.78rem;font-weight:600;color:var(--argon-dark);display:block;margin-bottom:.25rem">Status</label><select name="status" id="editStatus" style="width:100%;padding:.45rem .6rem;border:1px solid var(--argon-border);border-radius:.25rem;font-size:.82rem"><option value="active">Active</option><option value="suspended">Suspended</option><option value="banned">Banned</option></select></div><div><label style="font-size:.78rem;font-weight:600;color:var(--argon-dark);display:block;margin-bottom:.25rem">Balance ($)</label><input type="number" name="balance" id="editBalance" step="0.01" style="width:100%;padding:.45rem .6rem;border:1px solid var(--argon-border);border-radius:.25rem;font-size:.82rem"></div><div><label style="font-size:.78rem;font-weight:600;color:var(--argon-dark);display:block;margin-bottom:.25rem">Interest Balance ($)</label><input type="number" name="interest_balance" id="editInterest" step="0.01" style="width:100%;padding:.45rem .6rem;border:1px solid var(--argon-border);border-radius:.25rem;font-size:.82rem"></div><div style="display:flex;gap:.5rem;justify-content:flex-end"><button type="button" onclick="hideEditModal()" style="background:var(--argon-light);border:1px solid var(--argon-border);padding:.45rem 1.2rem;border-radius:.25rem;cursor:pointer;font-size:.82rem">Cancel</button><button type="submit" style="background:var(--argon-primary);color:#fff;border:none;padding:.45rem 1.2rem;border-radius:.25rem;cursor:pointer;font-weight:600;font-size:.82rem">Save</button></div></form></div></div></div>

<script>
let currentPage=1,searchTimeout;
function debounceSearch(){clearTimeout(searchTimeout);searchTimeout=setTimeout(()=>loadUsers(),300)}
async function loadUsers(page=1){currentPage=page;const s=document.getElementById('searchInput').value,st=document.getElementById('statusFilter').value,p=new URLSearchParams({page,limit:20});if(s)p.set('search',s);if(st)p.set('status',st);const r=await fetch(`/api/admin/users.php?${p}`),d=await r.json(),c=document.getElementById('usersList');if(!d.success||!d.data.users.length){c.innerHTML='<div class="tscroll"><table><tbody><tr><td colspan="8" style="text-align:center;padding:2rem;color:var(--argon-muted)">No users found.</td></tr></tbody></table></div>';document.getElementById('pagination').innerHTML='';return}c.innerHTML=`<div class="tscroll"><table><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>Balance</th><th>Status</th><th>KYC</th><th>Joined</th><th>Actions</th></tr></thead><tbody>${d.data.users.map(u=>`<tr><td>#${u.id}</td><td style="font-weight:600;color:var(--argon-dark)">${escHtml(u.first_name+' '+u.last_name)}</td><td>${escHtml(u.email)}</td><td>$${parseFloat(u.balance).toFixed(2)}</td><td><span class="badge ${u.status==='active'?'b-success':u.status==='suspended'?'b-warning':'b-danger'}">${u.status}</span></td><td><span class="badge ${u.kyc_status==='verified'?'b-success':'b-default'}">${u.kyc_status}</span></td><td style="font-size:.75rem;color:var(--argon-muted)">${u.created_at}</td><td><a href="#" onclick="viewUser(${u.id})" class="act-link" style="margin-right:.5rem">View</a><a href="#" onclick="editUser(${u.id},'${u.status}',${u.balance},${u.interest_balance})" class="act-link" style="color:var(--argon-warning)">Edit</a></td></tr>`).join('')}</tbody></table></div>`;const tp=Math.ceil(d.data.total/d.data.limit);let h='';for(let i=1;i<=tp;i++)h+=`<button onclick="loadUsers(${i})" style="padding:.35rem .85rem;border-radius:.25rem;font-size:.82rem;border:1px solid var(--argon-border);cursor:pointer;${i===currentPage?'background:var(--argon-primary);color:#fff;border-color:var(--argon-primary)':'background:var(--argon-white);color:var(--argon-text)'}">${i}</button>`;document.getElementById('pagination').innerHTML=h}
async function viewUser(id){const r=await fetch(`/api/admin/user-detail.php?id=${id}`),d=await r.json(),c=document.getElementById('detailContent');if(!d.success){c.innerHTML='<p style="color:var(--argon-danger)">Failed to load user.</p>'}else{const u=d.data.user;c.innerHTML=`<div style="display:grid;grid-template-columns:1fr 1fr;gap:.75rem;margin-bottom:1rem;font-size:.82rem"><div><span style="color:var(--argon-muted)">Name:</span> <strong>${escHtml(u.first_name+' '+u.last_name)}</strong></div><div><span style="color:var(--argon-muted)">Email:</span> <strong>${escHtml(u.email)}</strong></div><div><span style="color:var(--argon-muted)">Balance:</span> <strong>$${parseFloat(u.balance).toFixed(2)}</strong></div><div><span style="color:var(--argon-muted)">Interest:</span> <strong>$${parseFloat(u.interest_balance).toFixed(2)}</strong></div><div><span style="color:var(--argon-muted)">Status:</span> <strong>${u.status}</strong></div><div><span style="color:var(--argon-muted)">KYC:</span> <strong>${u.kyc_status}</strong></div></div><h6 style="margin-bottom:.5rem">Investments (${d.data.investments.length})</h6>${d.data.investments.length?`<div class="tscroll" style="margin-bottom:1rem"><table><thead><tr><th>Plan</th><th>Amount</th><th>Profit</th><th>Status</th></tr></thead><tbody>${d.data.investments.map(inv=>`<tr><td>${escHtml(inv.plan_name)}</td><td>$${parseFloat(inv.amount).toFixed(2)}</td><td>$${parseFloat(inv.total_profit).toFixed(2)}</td><td>${inv.status}</td></tr>`).join('')}</tbody></table></div>`:'<p style="color:var(--argon-muted);margin-bottom:1rem">None</p>'}<h6 style="margin-bottom:.5rem">Deposits (${d.data.deposits.length})</h6>${d.data.deposits.length?`<div class="tscroll" style="margin-bottom:1rem"><table><thead><tr><th>Amount</th><th>Method</th><th>Status</th></tr></thead><tbody>${d.data.deposits.map(dd=>`<tr><td>$${parseFloat(dd.amount).toFixed(2)}</td><td>${escHtml(dd.payment_method)}</td><td>${dd.status}</td></tr>`).join('')}</tbody></table></div>`:'<p style="color:var(--argon-muted);margin-bottom:1rem">None</p>'}<h6 style="margin-bottom:.5rem">Withdrawals (${d.data.withdrawals.length})</h6>${d.data.withdrawals.length?`<div class="tscroll"><table><thead><tr><th>Amount</th><th>Bank</th><th>Status</th></tr></thead><tbody>${d.data.withdrawals.map(w=>`<tr><td>$${parseFloat(w.amount).toFixed(2)}</td><td>${escHtml(w.bank_name)}</td><td>${w.status}</td></tr>`).join('')}</tbody></table></div>`:'<p style="color:var(--argon-muted)">None</p>'}`}document.getElementById('detailModal').style.display='flex'}
function editUser(id,status,balance,interestBalance){document.getElementById('editUserId').value=id;document.getElementById('editStatus').value=status;document.getElementById('editBalance').value=balance;document.getElementById('editInterest').value=interestBalance;document.getElementById('editModal').style.display='flex'}
function hideDetailModal(){document.getElementById('detailModal').style.display='none'}
function hideEditModal(){document.getElementById('editModal').style.display='none'}
document.getElementById('editForm').addEventListener('submit',async(e)=>{e.preventDefault();const f=new FormData(e.target);const r=await fetch('/api/admin/update-user.php',{method:'POST',body:f});const d=await r.json();showAlert(d.message,d.success?'success':'error');if(d.success){hideEditModal();loadUsers(currentPage)}});
function escHtml(s){const d=document.createElement('div');d.textContent=String(s);return d.innerHTML}
loadUsers();
</script>
<?php require_once __DIR__ . '/../includes/argon-footer.php'; ?>
