<?php
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/admin-session.php';
requireAdminLogin();
$admin = getCurrentAdmin();
$nav_type = 'admin'; $active_nav = 'withdrawals';
$page_title = 'Manage Withdrawals'; $page_subtitle = 'Approve or reject withdrawal requests';
require_once __DIR__ . '/../includes/argon-header.php';
?>
<div class="card" style="margin-bottom:1.25rem"><div class="card-body"><div style="display:flex;flex-wrap:wrap;gap:.75rem;align-items:flex-end"><div><label style="font-size:.78rem;font-weight:600;color:var(--argon-dark);display:block;margin-bottom:.25rem">Status</label><select id="statusFilter" onchange="loadWithdrawals()" style="padding:.45rem .6rem;border:1px solid var(--argon-border);border-radius:.25rem;font-size:.82rem"><option value="">All</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div></div></div></div>
<div id="withdrawalsList" class="card tsec"><div class="tscroll"><table><thead><tr><th>ID</th><th>User</th><th>Amount</th><th>Bank</th><th>Account #</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody><tr><td colspan="8" style="text-align:center;color:var(--argon-muted)">Loading...</td></tr></tbody></table></div></div>
<div id="pagination" style="display:flex;justify-content:center;gap:.5rem;margin-top:1rem"></div>
<div id="rejectModal" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:200;align-items:center;justify-content:center"><div class="card" style="max-width:460px;width:90%"><div class="card-header"><h6>Reject Withdrawal</h6></div><div class="card-body"><form id="rejectForm" style="display:flex;flex-direction:column;gap:.75rem"><input type="hidden" name="id" id="rejectId"><div><label style="font-size:.78rem;font-weight:600;color:var(--argon-dark);display:block;margin-bottom:.25rem">Reason</label><textarea name="reason" required rows="3" placeholder="Enter rejection reason..." style="width:100%;padding:.45rem .6rem;border:1px solid var(--argon-border);border-radius:.25rem;font-size:.82rem"></textarea></div><div style="display:flex;gap:.5rem;justify-content:flex-end"><button type="button" onclick="hideRejectModal()" style="background:var(--argon-light);border:1px solid var(--argon-border);padding:.45rem 1.2rem;border-radius:.25rem;cursor:pointer;font-size:.82rem">Cancel</button><button type="submit" style="background:var(--argon-danger);color:#fff;border:none;padding:.45rem 1.2rem;border-radius:.25rem;cursor:pointer;font-weight:600;font-size:.82rem">Reject & Refund</button></div></form></div></div></div>
<script>
let currentPage=1;
async function loadWithdrawals(page=1){currentPage=page;const st=document.getElementById('statusFilter').value,p=new URLSearchParams({page,limit:20});if(st)p.set('status',st);const r=await fetch(`/api/admin/withdrawals.php?${p}`),d=await r.json(),c=document.getElementById('withdrawalsList');if(!d.success||!d.data.withdrawals.length){c.innerHTML='<div class="tscroll"><table><tbody><tr><td colspan="8" style="text-align:center;padding:2rem;color:var(--argon-muted)">No withdrawals found.</td></tr></tbody></table></div>';document.getElementById('pagination').innerHTML='';return}c.innerHTML=`<div class="tscroll"><table><thead><tr><th>ID</th><th>User</th><th>Amount</th><th>Bank</th><th>Account #</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody>${d.data.withdrawals.map(w=>`<tr><td>#${w.id}</td><td><strong>${escHtml(w.first_name+' '+w.last_name)}</strong><br><span style="font-size:.72rem;color:var(--argon-muted)">${escHtml(w.email)}</span></td><td style="font-weight:600">$${parseFloat(w.amount).toFixed(2)}</td><td>${escHtml(w.bank_name)}</td><td>${escHtml(w.account_number)}<br><span style="font-size:.72rem;color:var(--argon-muted)">${escHtml(w.account_holder_name)}</span></td><td><span class="badge ${w.status==='approved'?'b-success':w.status==='pending'?'b-warning':'b-danger'}">${w.status}</span></td><td style="font-size:.75rem;color:var(--argon-muted)">${w.created_at}</td><td>${w.status==='pending'?`<a href="#" onclick="approveWithdrawal(${w.id})" class="act-link" style="color:var(--argon-success);margin-right:.5rem">Approve</a><a href="#" onclick="showRejectModal(${w.id})" class="act-link" style="color:var(--argon-danger)">Reject</a>`:'<span style="font-size:.75rem;color:var(--argon-muted)">—</span>'}</td></tr>`).join('')}</tbody></table></div>`;const tp=Math.ceil(d.data.total/d.data.limit);let h='';for(let i=1;i<=tp;i++)h+=`<button onclick="loadWithdrawals(${i})" style="padding:.35rem .85rem;border-radius:.25rem;font-size:.82rem;border:1px solid var(--argon-border);cursor:pointer;${i===currentPage?'background:var(--argon-primary);color:#fff;border-color:var(--argon-primary)':'background:var(--argon-white);color:var(--argon-text)'}">${i}</button>`;document.getElementById('pagination').innerHTML=h}
async function approveWithdrawal(id){if(!confirm('Approve this withdrawal?'))return;const f=new FormData();f.set('id',id);const r=await fetch('/api/admin/approve-withdrawal.php',{method:'POST',body:f});const d=await r.json();showAlert(d.message,d.success?'success':'error');if(d.success)loadWithdrawals(currentPage)}
function showRejectModal(id){document.getElementById('rejectId').value=id;document.getElementById('rejectModal').style.display='flex'}
function hideRejectModal(){document.getElementById('rejectModal').style.display='none'}
document.getElementById('rejectForm').addEventListener('submit',async(e)=>{e.preventDefault();const f=new FormData(e.target);const r=await fetch('/api/admin/reject-withdrawal.php',{method:'POST',body:f});const d=await r.json();showAlert(d.message,d.success?'success':'error');if(d.success){hideRejectModal();loadWithdrawals(currentPage)}});
function escHtml(s){const d=document.createElement('div');d.textContent=String(s);return d.innerHTML}
loadWithdrawals();
</script>
<?php require_once __DIR__ . '/../includes/argon-footer.php'; ?>
